---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack-grafana
  namespace: monitoring
spec:
  encryptedData:
    admin-user: AgARKEFfD521IPKVypDXiFN0YLKyxx39w0Fp3ajz0DhGANMD5tiXWboF2H0+A3xnsfz1+tcjsS6dQQmhZiByo+JsoZFAy8ikDBSuM+QQQIvPElGRvvm/Jh7i6wmVOfKXsL76c2BrX98au3zSJX74QsUVQxR9857B3wgf73ukFvv0AOKDksGGSLZUXw7G5OAI4nrB4CNKo/yTtdHSK4QiY2YvXxRcAS8cBJvegMX1H/mMDPc89yFcLFOXpbBTaBmM9LY9xIRBTcGGOS6i7gMR39vEEUV18tRGnBH1vpF95DdTjqtTYvqJkTQtAf4fuXz3X58G5xykdbsJxaDQStyP4XJbfsDY5K9LRXfZiq6B1/uLP4EoRQdkpiv//mxXuo7Heu4SNCyjqp6jPmJVsw1zSM5o+obrkhybxtT0ntkvSNUpNEB9CskqwI6ITnGaJD4ilGJW0EUgo5/PRK2dUgbUSPLct4YMSO+LbRR2Msqv1zCwosAWbgdHbA4hqO/SxqiAfcdoHtSap2QLb7CM89QzJp43koD4sJLFM+K2ZBDtB+Mn+tbtsMNjscNwFvxHBe7CTZ9p1sYNEDxsJEzC183XsXcGB+4SM0SICrAtaitQypyeALEtL1Qrqt5KPY75sSNjSr2fVnLfqY125Qlzf93dUAxmbN/wsjRoc2MeEG1OwvdCNu+MZwwEPNvTmB5M6LkME74ICI+JZQ==
    password-user: AgBWSnEZLG1BjZuSnRiBkG72Okwd4WO5VKLZvf8HQ4HSBxkXAyw7fcQv49WjZhqLappsKYLuo42Ei7Eifgm8x+BlYWXeifUif7dmMSCbJyj/S82o33GMjHmX/wsCNSiw6TtP1Tb47t2QXHSdTylpzeRzd+FlzcjhL9o5TA+Z4pzrVflTbeIwxuHZY9qO32K538KKLgWkpjLiebAtIGSNWhUhSsiFXvqHZLYiaMkq92s0JY7wuQTsgk0hqbwAXAZcJwPjMaEsGVcJtS/EAJp6UEwOv0r0fiHVZasWN5bKHA+gZ6u40UnXuSl2dsNVlB0DFKhfYuee5GNK4aJxBvWAn5Csqo2myx+BWRzyfs7N4iXZmLEnlNZwnRmRfjhFmbDIEgBtsMY9lCm0fpPEoSH22McRv5DrKvG9nCfjHLDkvahXOucyZG4MVg2LurtNdS9nEszHS/d2DMout3ju3RypLJ7BakPI2ijewgtXmYtPjDXT+QfYhhAP86EiDEmQC9AxNe6WZo71kBXWrfLReaVQChc1ZLhnk5Zgf5IDkXsuSkxIq0+qT3hTZChtqrVQhoLrI9/pUJio/77xQ/MdNtJAyqETik33y7TFYC/USW9ffXSYjlmUgN8vjOPpp5CSd94fPnpyOynNBn1h596Ke7omWN6SO2LC2e2M4KreyONEETrKvpWSlJM52+O34tfaiJEavYkAfAliQd6R8A==
  template:
    metadata:
      name: kube-prometheus-stack-grafana
      namespace: monitoring
    type: Opaque
