---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: glance-secrets
  namespace: glance
spec:
  encryptedData:
    github_token: AgCuYwWiIzK2Sqz8xvot7/Y/5vtuaifeXH79FGEGkR8imLwFOF1LVaNlF8Ky5YrtAduhREwrkQRvy86xUES6OL9aSv62Vc7j8Fd+o5i47f8g+3jWoKw5NUor6N4A2G2vIOwjqLTqN5CJMCnor5X19uSeRfDgYxmclEt4cOPn9X9jzwhl8joxgkR3XFdWLmZjjuc8gJgVPCXPUAfxwBWQdmEaZ2aHYPGuo98c5397ABnt5bmE2WcRUgkbS5HaiLdaA2j0/n+7gDCFO44NJ28Aq1bU34okGqCD87PzO7SF3qWPwQONJkbBntbPM7GvXK/dxWr3N4/bGFNbvyOniydzpIhjo7iT+ryLgxm1OmV584/1fsP61R250ah95LZGxTFVMwYE1MkO8i3j2c5d2EVF+wf3m95/vUwc/9TvTx4E/e8hiOfgrUjW6NRAPGJQHbQA9lGmkHHbnTerbzr48oiqWJibcuOoqpxtL7EhIdDC/SffuvR+Xu3r0z+JIdf5hVve+IJimWDYKVuAX3p4RXF2PZp0+oTUuufs/PxwWvpwCEI0jrq/Uhi2XAc7+DcRWGaZJCL28/a8lNabHPsRyK1Qp17MoWijGl518gwayXMZ8/vcXIiiBR328bprSTKuv50Xs7UX/sKIO5pXlwCaUmCG+BvQ0DEw4D96aN3xUSwA1nsTAoqYQOgxuo8+j03Z7Ln/vdbiNyScKO/eocAkANnDliXM+Fe7zggYGnB4AMIdI5iu9iEvzfWgr+sfcQ==
  template:
    metadata:
      name: glance-secrets
      namespace: glance
    type: Opaque
